CREATE TABLE [dbo].[Invoices]
(
	[Id] UNIQUEIDENTIFIER CONSTRAINT PK_Invoices_Id PRIMARY KEY DEFAULT NEWID(),
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Amount] DECIMAL(19,2) NOT NULL,
	[StartDate] DATETIME2 NOT NULL,
	[EndDate] DATETIME2 NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL CONSTRAINT DF_Invoices_CreatedOn DEFAULT GETUTCDATE(),
	CONSTRAINT FK_Invoices_Users FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id])
)
