CREATE TABLE [dbo].[OrderDesigns]
(
	[Id] INT CONSTRAINT PK_OrderDesigns_Id PRIMARY KEY IDENTITY(1,1),
	[OrderId] INT NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
    [CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL CONSTRAINT DF_OrderDesigns_CreatedOn DEFAULT GETUTCDATE(),
    CONSTRAINT FK_OrderDesigns_Orders FOREIGN KEY ([OrderId]) REFERENCES [dbo].[Orders]([Id]) ON DELETE CASCADE
)
