CREATE TABLE [dbo].[UserRoles]
(
	[Id] INT CONSTRAINT PK_UserRoles_Id PRIMARY KEY IDENTITY(1,1),
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Role] NVARCHAR(50) NULL,
	[Active] BIT NOT NULL CONSTRAINT DF_UserRoles_Active DEFAULT 1,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL CONSTRAINT DF_UserRoles_CreatedOn DEFAULT GETUTCDATE(),
    [UpdatedBy] UNIQUEIDENTIFIER NULL, 
    [UpdatedOn] DATETIME2 NULL,
    CONSTRAINT FK_UserRoles_Users FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE
)
