CREATE TABLE [dbo].[UserRoles]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[Role] NVARCHAR(50) NOT NULL,
    [SortOrder] INT NOT NULL,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedOn] DATETIME2 NOT NULL CONSTRAINT DF_UserRoles_CreatedOn DEFAULT GETUTCDATE(),
	CONSTRAINT PK_UserRoles PRIMARY KEY ([UserId],[Role]),
    CONSTRAINT FK_UserRoles_Users FOREIGN KEY ([UserId]) REFERENCES [dbo].[Users]([Id]) ON DELETE CASCADE
)
