// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CottonPrompt.Infrastructure.Entities;

public partial class InvoiceSection
{
    public int Id { get; set; }

    public Guid InvoiceId { get; set; }

    public string Name { get; set; }

    public decimal Rate { get; set; }

    public decimal Amount { get; set; }

    public int Quantity { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual ICollection<InvoiceSectionOrder> InvoiceSectionOrders { get; set; } = new List<InvoiceSectionOrder>();
}