// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CottonPrompt.Infrastructure.Entities;

public partial class InvoiceSectionOrder
{
    public int Id { get; set; }

    public int InvoiceSectionId { get; set; }

    public int OrderId { get; set; }

    public virtual InvoiceSection InvoiceSection { get; set; }

    public virtual Order Order { get; set; }
}