// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CottonPrompt.Infrastructure.Entities;

public partial class Order
{
    public int Id { get; set; }

    public string OrderNumber { get; set; }

    public bool Priority { get; set; }

    public string Concept { get; set; }

    public string PrintColor { get; set; }

    public int DesignBracketId { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public Guid? ArtistClaimedBy { get; set; }

    public DateTime? ArtistClaimedOn { get; set; }

    public Guid? CheckerClaimedBy { get; set; }

    public DateTime? CheckerClaimedOn { get; set; }

    public Guid? ApprovedBy { get; set; }

    public DateTime? ApprovedOn { get; set; }

    public Guid? UpdatedBy { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual OrderDesignBracket DesignBracket { get; set; }

    public virtual ICollection<OrderDesign> OrderDesigns { get; set; } = new List<OrderDesign>();

    public virtual ICollection<OrderImageReference> OrderImageReferences { get; set; } = new List<OrderImageReference>();
}