// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CottonPrompt.Infrastructure.Entities;

public partial class OrderDesignComment
{
    public int Id { get; set; }

    public int OrderDesignId { get; set; }

    public string Comment { get; set; }

    public Guid CreatedBy { get; set; }

    public DateTime CreatedOn { get; set; }

    public virtual OrderDesign OrderDesign { get; set; }
}